#!/bin/bash

profile="sso"
exportOnly=0
while getopts 'p:he' opt; do
  case "$opt" in
    p)
      profile="${OPTARG}"
      ;;
    h)
      echo "Usage: aws_init [-p <profile>]
      -p The profile to use (default: sso)
      -e Only export credentials, do not login
      -h Show this help
      "
      exit 0
      ;;
    e)
      exportOnly=1
      ;;
    *)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

if [[ exportOnly -ne 1 ]]; then
  if aws configure list-profiles | grep -q "$profile"; then
    aws sso login --profile "$profile"
  else
    aws configure sso --profile "$profile"
  fi
fi


credentials=$(aws configure export-credentials --profile "$profile")
if [ -z "$credentials" ]; then
  echo "Error: Failed to export credentials for profile '$profile'" >&2
  exit 1
fi

AWS_ACCESS_KEY_ID=$(echo "$credentials" | jq --raw-output ".AccessKeyId")
AWS_SECRET_ACCESS_KEY=$(echo "$credentials" | jq --raw-output ".SecretAccessKey")
AWS_SESSION_TOKEN=$(echo "$credentials" | jq --raw-output ".SessionToken")

export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
aws configure set aws_session_token "$AWS_SESSION_TOKEN"
