#!/bin/bash
if [[ ${#} -lt 1 ]]; then
  echo "Usage: assumerole [-o] <role_arn> [session_name] [profile_name]
  -o Override credentials in profile
  role_arn The ARN of the role to assume
  session_name The name of the session to use (default: username@hostname)
  profile_name The name of the profile to use (default: default), only used if -o is specified
  "
  exit 1
fi
override_profile=0

while getopts 'o' opt; do
  case "$opt" in
    o)
      override_profile=1
      ;;
    *)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND -1))

role_arn="${1}"
session_name="${2:-$(whoami)@$(hostname)}"
profile_name="${3:-default}"

output=$(
aws sts assume-role \
  --role-arn "$role_arn" \
  --role-session-name "$session_name" \
  --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
  --output text || {
    echo "Failed to assume role."
    exit 1
  }
)
read AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN <<< "$output"
export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
if aws sts get-caller-identity --profile "$profile_name" > /dev/null 2>&1; then
  echo "Current shell session assumed role successfully."
else
  echo "Failed to assume role."
  exit 1
fi
echo

if [[ "$override_profile" -eq 1 ]]; then
  echo "Outputting to profile..."
  aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $profile_name
  aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile $profile_name
  aws configure set aws_session_token $AWS_SESSION_TOKEN --profile $profile_name
  echo "Credentials updated in profile $profile_name"
fi


